[package]
name = "rust-lib"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"
build = "build/build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
winit = "0.19.1"

[build-dependencies]
cbindgen = "0.9.0"
